<h1> Términos y condiciones de la App</h1>

<p>
    Derechos de autor y marcas registradas
Todo el contenido es propiedad de Southern California Gas Company © 2000 - 2018.
Todos los derechos de autor y marcas registradas reservados.

Contenido
Todo texto, información, datos, fotografías, gráficos, código html, software informático, código fuente y código objeto, muestras de audio y video, marcas y logotipos, y similares (en adelante el "Contenido") que aparezcan en este sitio web optimizado para dispositivos móviles, servicios de dispositivos móviles o aplicaciones de dispositivos móviles (en conjunto "Aplicación Móvil") pertenecen a Southern California Gas Company (en adelante la "Compañía" o "SoCalGas") o sus empresas afiliadas, licenciatarios o proveedores, salvo que quede expresamente especificado en esta Aplicación Móvil. Los Usuarios (como se definen en el presente documento) solo pueden utilizar el Contenido en un dispositivo móvil (por ejemplo, Apple iPhone o iPad, dispositivo Android o dispositivo móvil con Microsoft Windows) que posean o controlen, y solamente por motivos personales, internos y sin fines comerciales. “© 2018 Southern California Gas Company. Todos los derechos reservados.” Ningún otro uso del Contenido, incluyendo, entre otras, cualquier clase de reedición del mismo, está permitido sin previa autorización por escrito otorgada por la Compañía. Todo Usuario que haya violado comprobadamente la propiedad intelectual de un tercero mediante la retransmisión o publicación de material vinculado con esta Aplicación Móvil que infrinja los derechos de autor u otros derechos legales de dicho tercero será excluido de esta Aplicación Móvil.

Todas las marcas registradas utilizadas en esta Aplicación Móvil son propiedad de la Compañía o, en unos pocos casos, utilizadas con la autorización de sus respectivos titulares. Ningún tercero puede utilizar ni reproducir ninguna marca registrada que incluya, entre otros, logotipos y dominios de Internet que utilicen las marcas registradas “SoCalGas”, “Southern California Gas” o “Southern California Gas Company” (ya sea que se usen o no con letras mayúsculas o espacios) sin el previo consentimiento por escrito de la Compañía o del propietario de la marca registrada.

Aparte del derecho de uso no exclusivo, no sublicenciable, intransferible, personal y limitado de los Usuarios tal como se especifica en la presente, no se confiere ningún derecho a dicho Contenido ni a porciones del mismo, sin importar la forma en que aparezca, mediante su inclusión en esta Aplicación Móvil o mediante el acceso al mismo por parte del Usuario. Un Usuario no puede: (a) separar ningún Contenido individual o componente de la Aplicación Móvil para otro uso que el indicado en relación a la Aplicación Móvil; (b) incorporar una porción del mismo a los propios programas del Usuario o recopilar cualquier porción en combinación con los propios programas del Usuario; (c) transferirlo para ser utilizado por otro servicio; o (d) vender, arrendar, ceder, prestar, distribuir, comunicar públicamente, transformar o sublicenciar la Aplicación Móvil o conceder en modo alguno cualquier derecho a la Aplicación Móvil absoluta o parcialmente. La Compañía será responsable de todo mantenimiento o soporte técnico de la Aplicación Móvil; ningún Tercero (como se define en el presente documento) será responsable de brindar servicios de mantenimiento o soporte técnico para la Aplicación Móvil.

La Compañía se reserva el derecho de enmendar, complementar o suspender total o parcialmente la Aplicación Móvil en forma ocasional. Asimismo, la Compañía se reserva el derecho de cambiar los Términos y Condiciones en cualquier momento, con vigencia inmediata a partir del momento que se actualiza la Aplicación Móvil. Los términos “Usuario” y “Usuarios” se refieren a todo individuo o entidad que use, acceda, descargue, instale, obtenga o brinde información desde y hacia esta Aplicación Móvil. Todas las referencias al plural en la presente incluirán al singular y las referencias al singular incluirán al plural salvo que se desprenda otra interpretación del contexto.

Reclamos por violación de derechos en la aplicación móvil
En caso de que un visitante crea que sus derechos de propiedad intelectual o marcas registradas puedan estar siendo violados por materiales publicados o almacenados en esta Aplicación Móvil, deberá completar la “Notificación de Violación de Derechos” del enlace y enviar un correo electrónico a nuestro webmaster: webmaster@socalgas.com con una copia de confirmación enviada a:

Southern California Gas Company
Office of the General Counsel
Notice of Infringement
555 W 5Th St.
Los Angeles, CA 90013-1046

Dicha Notificación debe brindar la información requerida en cumplimiento de las cláusulas aplicables de la Ley de derechos de autor para medios digitales en el nuevo milenio (Digital Millennium Copyright Act, DMCA), Título 17 del Código de los Estados Unidos, Sección 517 (c)(3)(A) (y todas sus modificatorias). Tal como se prevé en dicha Ley, toda notificación que alegue la violación de derechos que incumpla en forma sustancial con las cláusulas antes señaladas no será considerada como prueba fehaciente de "conocimiento real" o una "certidumbre de hechos o circunstancias en las cuales se evidencie una acción de violación de derechos". Por favor, envíe una Notificación por separado para cada caso que desee informar como un caso supuesto de violación de derechos de autor.
 
La Compañía ha adoptado e implementado una política que prevé la terminación, en circunstancias apropiadas, de las cuentas de los Usuarios que son infractores reincidentes o que son acusados ​​repetidamente de infracción.
Uso
Al usar, acceder, descargar, instalar, obtener o brindar información desde y hacia esta Aplicación Móvil, se considerará que los Usuarios han leído y aceptado estos Términos y Condiciones (incluyendo nuestra Política de Privacidad), que se incorpora al presente documento en virtud de esta referencia. El uso de esta Aplicación Móvil también estará sujeto a los Términos y Condiciones de SoCalGas.com y, si correspondiera, a los Términos y Condiciones de My Account. Tenga presente que todas las referencias al "sitio web" en nuestra Política de Privacidad también se consideran válidas para esta Aplicación Móvil, ya sea que se utilice en forma conjunta o independientemente del Sitio Web de la Compañía en www.socalgas.com.

Los Usuarios deben suspender el uso de esta Aplicación Móvil inmediatamente si no están de acuerdo o no aceptan todos estos Términos y Condiciones. La Compañía se reserva el derecho de eliminar o prohibir a cualquier Usuario la utilización de esta Aplicación Móvil a su sola discreción.

Cuentas de usuario
La Compañía puede, a su sola discreción, brindar acceso a los Usuarios a porciones restringidas de esta Aplicación Móvil, incluyendo, entre otros, una o más cuentas de Usuario donde pueda brindarse y/u obtenerse la información y servicios específicos de los clientes.

Los Usuarios que entren a dichas ubicaciones podrían estar sujetos a Términos y Condiciones adicionales según se especifique en relación a los servicios proporcionados. Los Usuarios con cuentas de servicio son responsables exclusivos de preservar la confidencialidad de toda información de acceso, la información de la cuenta del Usuario y todas las acciones u omisiones vinculadas con dicha cuenta.

Envío de contenidos
En caso de que un Usuario envíe imágenes digitales u otro contenido, incluidas todas las fotografías, ilustraciones, gráficos y texto (en forma conjunta, “Materiales”) a la Compañía a través de la Aplicación Móvil, tendrán validez los siguientes términos:

El Usuario solo podrá enviar a la Compañía, a través de la Aplicación Móvil, Materiales de los cuales posea todos los derechos de propiedad intelectual. Dicho de otro modo, si un Usuario envía una imagen digital a la Compañía, el Usuario debe poseer todos los derechos sobre dicha imagen o el Usuario debe tener la autorización de la persona propietaria de tales derechos. Los menores de edad no pueden enviar Materiales a la Compañía a través de la Aplicación Móvil. Asimismo, un Usuario no puede enviar ninguna información susceptible de identificación personal sobre un niño menor de 13 años de edad.
Por el presente el Usuario cede a la Compañía los derechos y licencias mundiales, sin exclusividad, libres de regalías y a perpetuidad para (a) reproducir, distribuir, transmitir, representar y exhibir públicamente los Materiales, total o parcialmente, de cualquier manera y en cualquier medio para transmitir información, existente en la actualidad o que se cree en el futuro (“Medios”), (b) modificar, adaptar, traducir y crear trabajos derivados de los Materiales, total o parcialmente, de cualquier manera y en cualesquiera Medios, y (c) otorgar sublicencias por los derechos antedichos, total o parcialmente, a terceros con o sin canon de concesión.
Por el presente el Usuario otorga a la Compañía y sus sublicenciatarios una licencia sin exclusividad, mundial y libre de regalías para usar todas las marcas registradas, nombres comerciales y los nombres e imágenes de todo individuo que aparezca en los Materiales. El Usuario otorga a la Compañía y sus sublicenciatarios el derecho a usar el nombre que el Usuario envíe en relación con los Materiales.
Terceros
Los prestadores de servicio de telefonía inalámbrica de los Usuarios, los fabricantes y vendedores de los dispositivos móviles en los que el Usuario descargue, instale, utilice o acceda a la Aplicación Móvil, el creador del sistema operativo para los dispositivos móviles de los Usuarios y el operador de cualquier tienda de aplicaciones o servicios similares mediante los cuales los usuarios obtengan la Aplicación Móvil, si existieran, (en conjunto, los “Terceros”) no son parte de estos Términos y Condiciones y no son propietarios ni responsables de la Aplicación Móvil. Los Terceros no brindan ninguna garantía en relación con la Aplicación Móvil. No son responsables del mantenimiento u otros servicios de soporte técnico de la Aplicación Móvil y no serán responsables ante ningún otro reclamo, pérdidas, imputación de responsabilidades, daños y perjuicios, costos o gastos vinculados con la Aplicación Móvil.

Los Usuarios reconocen y aceptan que los Terceros y sus empresas subsidiarias son terceros beneficiarios de estos Términos y Condiciones y que ellos tienen el derecho (y se asumirá que han aceptado tal derecho) de ejercer estos Términos y Condiciones ante los usuarios como terceros beneficiarios.

La Aplicación Móvil fue creada para la versión más reciente disponible en el mercado de los sistemas operativos de los dispositivos móviles de los Usuarios y pueden surgir inconvenientes de compatibilidad cuando se utilicen versiones anteriores. La cobertura de la red inalámbrica y la velocidad de la red de Wi-Fi varían según el proveedor y la ubicación geográfica. La Compañía no se responsabiliza por las limitaciones y/o fallas en el funcionamiento de ningún servicio inalámbrico o Wi-FI que se use para acceder a esta Aplicación Móvil ni por la seguridad de los servicios inalámbricos o Wi-Fi. Asimismo, la Compañía no se responsabiliza de los cargos o tarifas por uso de redes de datos, que son exclusiva responsabilidad del Usuario.

Actualizaciones de la aplicación móvil
La Compañía puede solicitar a los Usuarios que actualicen su versión de la Aplicación Móvil en cualquier momento. Aunque se harán todos los esfuerzos por conservar las configuraciones y preferencias personales de los Usuarios, seguirá existiendo la posibilidad de que las mismas se pierdan.

Problemas de cobertura inalámbrica y desactivación de funciones
Al intentar realizar una transacción en la Aplicación Móvil, es posible que la conexión inalámbrica se interrumpa o que se desactive una función. En caso de que esto ocurriera, los Usuarios deberán verificar el estado de la transacción que se haya intentado realizar apenas ingresen a un área con cobertura inalámbrica o tengan acceso a una computadora. Los Usuarios también pueden ponerse en contacto con un representante de servicio al cliente de SoCalGas a través del enlace “Contáctenos” que se brinda a continuación:

Usuarios finales del gobierno de los Estados Unidos de América
Todo software informático que sea parte de la Aplicación Móvil y esté disponible para descarga o uso es un “Elemento Comercial” como se define en la § 2.101 del título 48 del Código Federal de Regulaciones (C.F.R.) compuesto por “software informático comercial” y “documentación de software informático comercial”, como se definen los términos la § 12.212 del título 48 del Código Federal de Regulaciones (C.F.R.) o la § 227.7202 del título 48 del Código Federal de Regulaciones (C.F.R.), según corresponda. En consonancia con estas cláusulas, dicho software informático es cedido con licencia a los usuarios finales del Gobierno de los Estados Unidos de América (a) solo como un Elemento Comercial, y (b) solo con aquellos derechos que se conceden al resto de los usuarios finales en cumplimiento con estos Términos y Condiciones. Los derechos no publicados son derechos reservados conforme a las leyes sobre derechos de autor de los EE. UU. de América.

Responsabilidad limitada
LOS TERCEROS, LA COMPAÑÍA Y SUS EMPRESAS MATRICES Y AFILIADAS, JUNTO CON LOS RESPECTIVOS DIRECTIVOS, DIRECTORES, PERSONAL, EMPLEADOS Y REPRESENTANTES (EN CONJUNTO REFERIDOS COMO LAS “PARTES EXENTAS”) NO SERÁN RESPONSABLES NI ESTARÁN SUJETOS A ACCIONES LEGALES, Y POR LA PRESENTE EL USUARIO RENUNCIA A TODO RECLAMO, DEMANDA, IMPUTACIÓN DE RESPONSABILIDADES, CAUSA LEGAL, QUERELLA, RECLAMACIÓN DE DAÑOS Y PERJUICIOS, POR RAZÓN DE, ENTRE OTROS, DAÑOS DIRECTOS, INDIRECTOS, ACCIDENTALES, INCIDENTALES, DERIVADOS, CIRCUNSTANCIALES, EXTRAORDINARIOS, ESPECIALES O PUNITIVOS DE CUALQUIER NATURALEZA CON RESPECTO A ESTA APLICACIÓN MÓVIL (INCLUYENDO LOS PRODUCTOS, SERVICIOS Y CONTENIDOS DE LAS PARTES EXENTAS), AÚN CUANDO LAS PARTES EXENTAS HUBIERAN SIDO ADVERTIDAS DE LA POSIBILIDAD DE DICHOS DAÑOS. EL ÚNICO RECURSO DE LOS USUARIOS ANTE TALES RECLAMOS, DEMANDAS, IMPUTACIÓN DE RESPONSABILIDADES, CAUSAS LEGALES, QUERELLAS O RECLAMOS DE DAÑOS Y PERJUICIOS ES PONER FIN AL USO DE ESTA APLICACIÓN MÓVIL.

Privacidad
Nuestra política de privacidad en relación a cualquier información obtenida por la Compañía a través de esta Aplicación Móvil puede consultarse en la sección Política de Privacidad del Sitio Web de la Compañía. Pueden tener validez algunas reglas adicionales en materia de privacidad según se establece en las funciones de esta Aplicación Móvil restringidas para servicios específicos del Usuario.

El uso de esta Aplicación Móvil implica la transmisión electrónica de información a través de las redes del proveedor de servicio inalámbrico. En vista de que la Compañía no opera ni controla las redes inalámbricas utilizadas para acceder a la Aplicación Móvil, la Compañía no es responsable de la privacidad o seguridad de las transmisiones inalámbricas de datos. Los Usuarios deberán utilizar proveedores de servicios acreditados y verificar junto a su proveedor de servicios inalámbricos la información relativa a sus prácticas en materia de privacidad y seguridad.

Patrocinio
La Compañía no recomienda, patrocina ni promociona negocios, servicios o productos de terceros, a excepción de manifestaciones de recomendación o patrocinio que la Compañía realice de manera expresa, si las hubiere, en esta Aplicación Móvil. Si esta Aplicación Móvil proporciona información sobre terceros o proporciona contenido de terceros, e incluso enlaces a sitios web de terceros, la Compañía no será responsable de ningún daño o perjuicio relacionado con cualquier información de terceros, aunque ésta contenga errores o equivocaciones. Asimismo, la Compañía no será responsable ni estará sujeta a acción legal por los servicios o productos de terceros. Consulte también la sección en materia de enlaces de nuestra Política de privacidad, incluido el descargo de responsabilidad por los contendidos de terceros.

Exclusión de garantía
LAS PARTES EXENTAS NO HACEN MANIFESTACIÓN ALGUNA EN CUANTO A LA FUNCIONALIDAD Y USO DEL CONTENIDO DE ESTA APLICACIÓN MÓVIL. EL USO Y NAVEGACIÓN QUE HAGA EL USUARIO CON ESTA APLICACIÓN MÓVIL ES A RIESGO EXCLUSIVO DEL PROPIO USUARIO. TODA LA INFORMACIÓN CONTENIDA EN ESTA APLICACIÓN MÓVIL ES PROPORCIONADA "TAL COMO ESTÁ” Y “SEGÚN ESTÁ DISPONIBLE”, SIN ASEVERACIONES NI GARANTÍAS, YA SEAN EXPRESAS O TÁCITAS. LOS USUARIOS NO DEBEN ASUMIR QUE LA INFORMACIÓN INCLUIDA EN ESTA APLICACIÓN MÓVIL SE ACTUALIZA CONSTANTEMENTE NI QUE INCLUYE INFORMACIÓN RECIENTE.

ESTA APLICACIÓN MÓVIL PODRÁ DEJAR DE FUNCIONAR, SER INTERRUMPIDA O FUNCIONAR INDEBIDAMENTE DE FORMA OCASIONAL. LAS PARTES EXENTAS NO TIENEN RESPONSABILIDAD POR DICHO CESE DE FUNCIONAMIENTO, INTERRUPCIÓN O FUNCIONAMIENTO INDEBIDO. LOS USUARIOS QUEDAN ADVERTIDOS DE QUE LA INFORMACIÓN CONTENIDA AQUÍ PODRÍA CONTENER ERRORES TÉCNICOS, INEXACTITUDES, ERRORES DE PROGRAMACIÓN, VIRUS DESCONOCIDOS Y OMISIONES. EL USUARIO ASUME TODOS LOS RIESGOS VINCULADOS CON EL USO DE ESTA APLICACIÓN MÓVIL, Y ACEPTA QUE LA COMPAÑÍA RENUNCIA A TODA GARANTÍA VINCULADA AL USO DE LA APLICACIÓN MÓVIL POR PARTE DEL USUARIO.

SIN PERJUICIO DE LO DISPUESTO EN CUALQUIER OTRA CLÁUSULA DE ESTOS TÉRMINOS Y CONDICIONES, LA COMPAÑÍA RECHAZA TODA MANIFESTACIÓN O GARANTÍA, YA SEA EXPRESA O TÁCITA, DE TODO TIPO EN REFERENCIA A ESTA APLICACIÓN MÓVIL (INCLUYENDO NUESTROS PRODUCTOS, SERVICIOS Y CONTENIDO DEL SITIO) INCLUIDAS, ENTRE OTRAS, LAS GARANTÍAS DE COMERCIABILIDAD Y APTITUD PARA UN PROPÓSITO EN PARTICULAR, DE GOCE PACÍFICO, TÍTULO, NO VIOLACIÓN DE LOS DERECHOS DE TERCEROS Y PRECISIÓN. NINGUNA INFORMACIÓN O ASESORAMIENTO ORAL O ESCRITO DADO POR NOSOTROS O NUESTROS REPRESENTANTES AUTORIZADOS CREARÁ UNA GARANTÍA NI AUMENTARÁ DE NINGUNA FORMA EL ALCANCE DE NUESTRAS OBLIGACIONES TAL CUAL SE ESTABLECEN EN ESTOS TÉRMINOS Y CONDICIONES.

Exoneración
Los Usuarios liberarán de toda responsabilidad y exonerarán a las Partes Exentas de todo reclamo, demanda, responsabilidad civil, causa legal, querella o daños y perjuicios (incluidos los honorarios y los gastos razonables de abogados) que surjan como consecuencia del uso que dichos Usuarios hagan de la Aplicación Móvil (incluidos nuestros productos, servicios y Contenido), incluyendo, entre otros, la información, contenido o entrega incorrectos de la Aplicación Móvil, o de los productos y servicios de la Compañía o de terceros. La Compañía se reserva el derecho, por cuenta propia, de asumir la defensa y el control exclusivos de cualquier asunto sujeto a exoneración por parte de los Usuarios, pero el hacerlo no exime a los Usuarios de sus obligaciones de exoneración.

Restricciones a la exportación
Esta Aplicación Móvil o su tecnología subyacente no pueden ser descargadas, exportadas ni reexportadas: a) a Cuba, Irán, Corea del Norte, Sudán, Siria ni a ningún otro país sujeto a medidas de embargo por parte de los EE. UU. (ni a un residente o ciudadano de estos países); (b) a cualquier persona que esté en la lista de Nacionales Especialmente Designados (Specially Designated Nationals) por el Departamento del Tesoro de los EE. UU. o en la lista de Personas Físicas o Jurídicas Denegadas (Denied Party or Entity List) del Departamento de Comercio de los EE. UU., y (c) a cualquier país, persona, usuario final o entidad prohibidos conforme a las leyes de exportación de los EE. UU.

Funciones de localización disponibles
Ciertas funciones de localización (por ejemplo, localizar la oficina de pago de la Compañía más cercana o la estación de GNC más cercana) disponibles en la Aplicación Móvil son provistas por terceros. El uso que hagan los usuarios de esa funcionalidad está sujeta a los términos y condiciones del tercero (y a sus actualizaciones ocasionales). Los usuarios deben utilizar su propio juicio sobre la adecuación e idoneidad de la información. Toda la información de localización es brindada por completo en las condiciones en que se encuentra, sin garantías de ninguna naturaleza.

Resolución de disputas
Acuerdo sobre el arbitraje de disputas
MEDIANTE EL USO, ACCESO, DESCARGA, INSTALACIÓN, OBTENCIÓN O PROVISIÓN DE INFORMACIÓN DESDE Y HACIA ESTA APLICACIÓN MÓVIL, LOS USUARIOS ACUERDAN EXPRESAMENTE QUE TODO RECLAMO, DISPUTA O CONTROVERSIA DE ÍNDOLE LEGAL ENTRE LOS USUARIOS Y LA COMPAÑÍA QUE SURJAN SURGIDOS O ESTÉN VINCULADOS DE CUALQUIER MODO CON LA APLICACIÓN MÓVIL, INCLUIDAS LAS CONTROVERSIAS VINCULADAS CON LA APLICABILIDAD, ALCANCE O VALIDEZ DE CUALQUIERA DE LAS CLÁUSULAS DE ESTOS TÉRMINOS Y CONDICIONES O DE NUESTRA POLÍTICA DE PRIVACIDAD (EN FORMA CONJUNTA, “DISPUTAS”) SERÁN RESUELTAS DE ACUERDO CON LOS PROCEDIMIENTOS AQUÍ ESTABLECIDOS. CUALQUIERA DE LAS PARTES PUEDE PRESENTAR UN RECLAMO CONTRA LA COMPAÑÍA HACIENDO CLIC AQUÍ. EN CASO DE QUE EL RECLAMO NO SE RESUELVA INFORMALMENTE, EL USUARIO ACEPTA POR LA PRESENTE RESOLVER TODAS LAS DISPUTAS MEDIANTE ARBITRAJE VINCULANTE CONFIDENCIAL, SALVO POR LA ÚNICA EXCEPCIÓN QUE SE ESTABLECE MÁS ADELANTE. TODAS LAS DISPUTAS SERÁN RESUELTAS POR UN ÁRBITRO, QUE SERÁ UN ÁRBITRO NEUTRAL DESIGNADO POR ACUERDO DE AMBAS PARTES DE LA DISPUTA. EN CASO DE QUE LAS PARTES NO LOGREN ACORDAR UN ÁRBITRO NEUTRAL LUEGO DE SESENTA (60) DÍAS, JAMS SELECCIONARÁ EL ÁRBITRO NEUTRAL PARA RESOLVER LA DISPUTA. LA COMPAÑÍA CUBRIRÁ LOS COSTOS DEL ÁRBITRO SELECCIONADO POR MEDIO DE ESTE PROCEDIMIENTO DE ACUERDO MUTUO PARA TODOS LOS RECLAMOS DE NATURALEZA NO FRÍVOLA. EL ARBITRAJE SE CELEBRARÁ DE ACUERDO A LAS REGLAS Y PROCEDIMIENTOS INTEGRALES DE ARBITRAJE DE JAMS, PUBLICADOS ENWWW.JAMSADR.COM. LOS USUARIOS ACEPTAN ESPECÍFICAMENTE QUE ESTÁN OBLIGADOS A RESOLVER TODAS LAS DISPUTAS MEDIANTE ARBITRAJE, INCLUYENDO, ENTRE OTROS, LA CAPACIDAD DE HACER VALER ESTE ACUERDO DE ARBITRAJE, SALVO QUE DECIDAN INICIAR UNA ACCIÓN LEGAL EN UN JUZGADO DE DEMANDAS DE MENOR CUANTÍA COMO SE ESTABLECE MÁS ADELANTE. Cada una de las partes acepta pagar los honorarios y gastos de sus propios abogados. Asimismo, el Usuario y la Compañía aceptan que para todo reclamo por daños de menos de $10,000, el arbitraje puede realizarse a criterio del demandante solamente basándose en presentaciones escritas. El Usuario y la Compañía también aceptan que para toda disputa de menos de $10,000, el cliente de la compañía de servicios públicos puede optar por presentar dicho reclamo en un juzgado de demandas de menor cuantía del condado en que el cliente tenga domicilio de facturación, y para todos los otros casos en un juzgado de demandas de menor cuantía de Los Angeles, California. Si la disputa es presentada por un cliente de servicios públicos de la Compañía, el arbitraje se celebrará en el condado donde el usuario tenga domicilio de facturación. Si la disputa es presentada por cualquier otra parte, el arbitraje deberá celebrarse en Los Angeles, California. El árbitro tiene la potestad de otorgar un interdicto judicial, pero no tiene la potestad de conceder daños punitivos. La disputa se regirá por las leyes de California, sin perjuicio de conflicto con las cláusulas de la ley.

Renuncia a arbitraje colectivo
En la medida que la plena aplicación de las leyes lo permita, todas las Disputas se resolverán por arbitraje vinculante confidencial en forma individual según la capacidad individual de cada parte, y no como parte integrante de una supuesta demanda colectiva de ninguna acción legal colectiva. El árbitro no tiene la capacidad legal de resolver más que el reclamo de una sola persona, y de ninguna manera puede dirimir ninguna forma de acción legal representativa o colectiva. Los Usuarios aceptan expresamente que ninguna otra Disputa será unificada ni anexada a su Disputa, ya sea mediante acciones legales de arbitraje colectivo u otros procedimientos. Mediante el uso, acceso, descarga, instalación, obtención o provisión de información desde o hacia esta Aplicación Móvil, los Usuarios aceptan que renuncian en forma voluntaria y deliberada a cualquier derecho a participar como representante o miembro de cualquier grupo o colectivo de demandantes de cualquier Disputa.

Cumplimiento de la decisión del arbitraje
La decisión del árbitro será final y vinculante para todas las partes sujetas a estos Términos y Condiciones, y puede ser aplicada como precedente en cualquier juzgado de jurisdicción competente.

Divisibilidad
Si cualquier cláusula de estos Términos y Condiciones resultara inválida, nula o inaplicable, las cláusulas restantes conservarán de todos modos su total validez y la cláusula inválida, nula o inaplicable será considerada como modificada de modo tal que sea válida y aplicable hasta el máximo alcance permitido por la ley.

Términos adicionales para dispositivos Apple
Esta sección se aplica exclusivamente a los Usuarios que utilicen la Aplicación Móvil en un dispositivo Apple (por ejemplo, iPhone, iPad, iPod Touch) (en adelante, denominados “Dispositivo Apple”). La Compañía solamente es responsable de la Aplicación Móvil que usted utiliza en su Dispositivo Apple, y los Usuarios pueden utilizar la Aplicación Móvil en su Dispositivo Apple solamente como se permite en estos Términos y Condiciones y en las “Normas de uso” establecidas en los Términos y Condiciones de la Tienda de Aplicaciones (http://www.apple.com/legal/itunes/appstore/us/terms.html). En relación con el deslinde de responsabilidades entre la Compañía y Apple Inc., en la medida en que: (a) la Compañía debe atender todo reclamo vinculado con el uso o posesión por parte del Usuario o de un tercero de la Aplicación Móvil en el Dispositivo Apple del Usuario, y la compañía será responsable de atender, investigar o defender el reclamo; y (b) la Compañía no ha renunciado efectivamente a ninguna garantía vinculada con la Aplicación Móvil en el Dispositivo Apple del Usuario, se desprende que la Compañía será responsable exclusiva en relación con cualquier garantía del producto u otros reclamos, pérdidas, imputación de responsabilidades, daños y perjuicios, costos o gastos si la Aplicación Móvil no se ajusta a ninguna de las garantías. Si la Aplicación Móvil en el Dispositivo Apple del Usuario no se ajusta a ninguna de las garantías pertinentes, el Usuario puede solicitar a Apple Inc. un reembolso por la suma de la compra de la Aplicación Móvil en el Dispositivo Apple del Usuario, si la hubiera. Apple Inc. no tendrá obligaciones de garantía de ninguna otra naturaleza con respecto a la Aplicación Móvil en el Dispositivo Apple del Usuario. Apple Inc. y sus filiales son terceros exentos de estos Términos y Condiciones, y Apple Inc. y sus filiales pueden hacer valer estos Términos y Condiciones contra los Usuarios en calidad de terceros exentos de estos Términos y Condiciones.

Idioma prevaleciente
En el caso de que existiera alguna inconsistencia, ambigüedad o conflicto entre la versión en inglés de estos Términos y Condiciones y las traducidas a otros idiomas, la versión en inglés prevalecerá sobre el resto.
</p>